# Generated by Django 3.1.3 on 2020-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldanalysis',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
