# Generated by Django 3.1.3 on 2020-11-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_crop_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='finished',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_type', models.IntegerField(choices=[(1, 'Nitrogen'), (2, 'Phosphorus'), (3, 'Magnesium')], default=1)),
                ('registration_type', models.IntegerField(choices=[(1, 'Automatic'), (2, 'Manual')], default=1)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.fieldanalysis')),
            ],
        ),
    ]
